(cl:defpackage platooning-msg
  (:use )
  (:export
   "<ACCELERATION>"
   "ACCELERATION"
   "<DISTANCETOOBJ>"
   "DISTANCETOOBJ"
   "<PLATOONPROTOCOL>"
   "PLATOONPROTOCOL"
   "<STEERINGANGLE>"
   "STEERINGANGLE"
   "<TARGETANGLE>"
   "TARGETANGLE"
   "<TARGETDISTANCE>"
   "TARGETDISTANCE"
   "<TARGETSPEED>"
   "TARGETSPEED"
   "<TEMPLATEMSG>"
   "TEMPLATEMSG"
   "<USERINTERFACE>"
   "USERINTERFACE"
  ))

