(cl:in-package platooning-msg)
(cl:export '(LEADING_VEHICLE-VAL
          LEADING_VEHICLE
          FOLLOWING_VEHICLE-VAL
          FOLLOWING_VEHICLE
          POTENTIAL_FOLLOWING_VEHICLE-VAL
          POTENTIAL_FOLLOWING_VEHICLE
          INNER_PLATOON_DISTANCE-VAL
          INNER_PLATOON_DISTANCE
          ACTUAL_DISTANCE-VAL
          ACTUAL_DISTANCE
          PLATOON_SPEED-VAL
          PLATOON_SPEED
          SPEED-VAL
          SPEED
          PLATOONING_STATE-VAL
          PLATOONING_STATE
          SRC_VEHICLE-VAL
          SRC_VEHICLE
          PLATOON_SIZE-VAL
          PLATOON_SIZE
          PLATOON_MEMBERS-VAL
          PLATOON_MEMBERS
          ENABLE_REMOTECONTROL-VAL
          ENABLE_REMOTECONTROL
))