# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from platooning/remotecontrolInput.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class remotecontrolInput(genpy.Message):
  _md5sum = "48eff1d5f037dfb934e32ce687673a3f"
  _type = "platooning/remotecontrolInput"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint32 vehicle_id
float32 remote_speed
float32 remote_angle
bool emergency_stop"""
  __slots__ = ['vehicle_id','remote_speed','remote_angle','emergency_stop']
  _slot_types = ['uint32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       vehicle_id,remote_speed,remote_angle,emergency_stop

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(remotecontrolInput, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.vehicle_id is None:
        self.vehicle_id = 0
      if self.remote_speed is None:
        self.remote_speed = 0.
      if self.remote_angle is None:
        self.remote_angle = 0.
      if self.emergency_stop is None:
        self.emergency_stop = False
    else:
      self.vehicle_id = 0
      self.remote_speed = 0.
      self.remote_angle = 0.
      self.emergency_stop = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_I2fB().pack(_x.vehicle_id, _x.remote_speed, _x.remote_angle, _x.emergency_stop))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.vehicle_id, _x.remote_speed, _x.remote_angle, _x.emergency_stop,) = _get_struct_I2fB().unpack(str[start:end])
      self.emergency_stop = bool(self.emergency_stop)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_I2fB().pack(_x.vehicle_id, _x.remote_speed, _x.remote_angle, _x.emergency_stop))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.vehicle_id, _x.remote_speed, _x.remote_angle, _x.emergency_stop,) = _get_struct_I2fB().unpack(str[start:end])
      self.emergency_stop = bool(self.emergency_stop)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_I2fB = None
def _get_struct_I2fB():
    global _struct_I2fB
    if _struct_I2fB is None:
        _struct_I2fB = struct.Struct("<I2fB")
    return _struct_I2fB
