// Generated by gencpp from file platooning/acceleration.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_ACCELERATION_H
#define PLATOONING_MESSAGE_ACCELERATION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct acceleration_
{
  typedef acceleration_<ContainerAllocator> Type;

  acceleration_()
    : accelleration(0.0)  {
    }
  acceleration_(const ContainerAllocator& _alloc)
    : accelleration(0.0)  {
  (void)_alloc;
    }



   typedef float _accelleration_type;
  _accelleration_type accelleration;





  typedef boost::shared_ptr< ::platooning::acceleration_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::acceleration_<ContainerAllocator> const> ConstPtr;

}; // struct acceleration_

typedef ::platooning::acceleration_<std::allocator<void> > acceleration;

typedef boost::shared_ptr< ::platooning::acceleration > accelerationPtr;
typedef boost::shared_ptr< ::platooning::acceleration const> accelerationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::acceleration_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::acceleration_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::acceleration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::acceleration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::acceleration_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::acceleration_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::acceleration_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::acceleration_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::acceleration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5cb03383b65207f8a255b5fa95fedef3";
  }

  static const char* value(const ::platooning::acceleration_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5cb03383b65207f8ULL;
  static const uint64_t static_value2 = 0xa255b5fa95fedef3ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::acceleration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/acceleration";
  }

  static const char* value(const ::platooning::acceleration_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::acceleration_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 accelleration\n\
";
  }

  static const char* value(const ::platooning::acceleration_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::acceleration_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accelleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct acceleration_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::acceleration_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::acceleration_<ContainerAllocator>& v)
  {
    s << indent << "accelleration: ";
    Printer<float>::stream(s, indent + "  ", v.accelleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_ACCELERATION_H
