// Generated by gencpp from file platooning/camera.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_CAMERA_H
#define PLATOONING_MESSAGE_CAMERA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct camera_
{
  typedef camera_<ContainerAllocator> Type;

  camera_()
    : pic()  {
    }
  camera_(const ContainerAllocator& _alloc)
    : pic(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pic_type;
  _pic_type pic;





  typedef boost::shared_ptr< ::platooning::camera_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::camera_<ContainerAllocator> const> ConstPtr;

}; // struct camera_

typedef ::platooning::camera_<std::allocator<void> > camera;

typedef boost::shared_ptr< ::platooning::camera > cameraPtr;
typedef boost::shared_ptr< ::platooning::camera const> cameraConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::camera_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::camera_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::camera_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::camera_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::camera_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::camera_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::camera_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::camera_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b029feab08f2c4877092228da5ee6702";
  }

  static const char* value(const ::platooning::camera_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb029feab08f2c487ULL;
  static const uint64_t static_value2 = 0x7092228da5ee6702ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/camera";
  }

  static const char* value(const ::platooning::camera_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::camera_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string pic\n\
";
  }

  static const char* value(const ::platooning::camera_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::camera_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pic);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct camera_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::camera_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::camera_<ContainerAllocator>& v)
  {
    s << indent << "pic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pic);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_CAMERA_H
