// Generated by gencpp from file platooning/distanceToObj.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_DISTANCETOOBJ_H
#define PLATOONING_MESSAGE_DISTANCETOOBJ_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct distanceToObj_
{
  typedef distanceToObj_<ContainerAllocator> Type;

  distanceToObj_()
    : distance_to_obj(0.0)  {
    }
  distanceToObj_(const ContainerAllocator& _alloc)
    : distance_to_obj(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_to_obj_type;
  _distance_to_obj_type distance_to_obj;





  typedef boost::shared_ptr< ::platooning::distanceToObj_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::distanceToObj_<ContainerAllocator> const> ConstPtr;

}; // struct distanceToObj_

typedef ::platooning::distanceToObj_<std::allocator<void> > distanceToObj;

typedef boost::shared_ptr< ::platooning::distanceToObj > distanceToObjPtr;
typedef boost::shared_ptr< ::platooning::distanceToObj const> distanceToObjConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::distanceToObj_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::distanceToObj_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::distanceToObj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::distanceToObj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::distanceToObj_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::distanceToObj_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::distanceToObj_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::distanceToObj_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::distanceToObj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b94f75528a81496ec1f35e38db49c1c0";
  }

  static const char* value(const ::platooning::distanceToObj_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb94f75528a81496eULL;
  static const uint64_t static_value2 = 0xc1f35e38db49c1c0ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::distanceToObj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/distanceToObj";
  }

  static const char* value(const ::platooning::distanceToObj_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::distanceToObj_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance_to_obj\n\
";
  }

  static const char* value(const ::platooning::distanceToObj_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::distanceToObj_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance_to_obj);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct distanceToObj_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::distanceToObj_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::distanceToObj_<ContainerAllocator>& v)
  {
    s << indent << "distance_to_obj: ";
    Printer<float>::stream(s, indent + "  ", v.distance_to_obj);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_DISTANCETOOBJ_H
