// Generated by gencpp from file platooning/fv_request.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_FV_REQUEST_H
#define PLATOONING_MESSAGE_FV_REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct fv_request_
{
  typedef fv_request_<ContainerAllocator> Type;

  fv_request_()
    : src_vehicle(0)  {
    }
  fv_request_(const ContainerAllocator& _alloc)
    : src_vehicle(0)  {
  (void)_alloc;
    }



   typedef uint32_t _src_vehicle_type;
  _src_vehicle_type src_vehicle;





  typedef boost::shared_ptr< ::platooning::fv_request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::fv_request_<ContainerAllocator> const> ConstPtr;

}; // struct fv_request_

typedef ::platooning::fv_request_<std::allocator<void> > fv_request;

typedef boost::shared_ptr< ::platooning::fv_request > fv_requestPtr;
typedef boost::shared_ptr< ::platooning::fv_request const> fv_requestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::fv_request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::fv_request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::fv_request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::fv_request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::fv_request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::fv_request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::fv_request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::fv_request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::fv_request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "07b1b45a74ecd2446be6ced3738fb3a9";
  }

  static const char* value(const ::platooning::fv_request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x07b1b45a74ecd244ULL;
  static const uint64_t static_value2 = 0x6be6ced3738fb3a9ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::fv_request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/fv_request";
  }

  static const char* value(const ::platooning::fv_request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::fv_request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 src_vehicle\n\
";
  }

  static const char* value(const ::platooning::fv_request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::fv_request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.src_vehicle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct fv_request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::fv_request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::fv_request_<ContainerAllocator>& v)
  {
    s << indent << "src_vehicle: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.src_vehicle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_FV_REQUEST_H
