// Generated by gencpp from file platooning/gazupdate.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_GAZUPDATE_H
#define PLATOONING_MESSAGE_GAZUPDATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct gazupdate_
{
  typedef gazupdate_<ContainerAllocator> Type;

  gazupdate_()
    : id(0)
    , distance(0.0)
    , speed(0.0)  {
    }
  gazupdate_(const ContainerAllocator& _alloc)
    : id(0)
    , distance(0.0)
    , speed(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef float _distance_type;
  _distance_type distance;

   typedef float _speed_type;
  _speed_type speed;





  typedef boost::shared_ptr< ::platooning::gazupdate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::gazupdate_<ContainerAllocator> const> ConstPtr;

}; // struct gazupdate_

typedef ::platooning::gazupdate_<std::allocator<void> > gazupdate;

typedef boost::shared_ptr< ::platooning::gazupdate > gazupdatePtr;
typedef boost::shared_ptr< ::platooning::gazupdate const> gazupdateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::gazupdate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::gazupdate_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::gazupdate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::gazupdate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::gazupdate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::gazupdate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::gazupdate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::gazupdate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::gazupdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e013a91e1d04c1d0c4b05e286456c85e";
  }

  static const char* value(const ::platooning::gazupdate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe013a91e1d04c1d0ULL;
  static const uint64_t static_value2 = 0xc4b05e286456c85eULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::gazupdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/gazupdate";
  }

  static const char* value(const ::platooning::gazupdate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::gazupdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n\
float32 distance\n\
float32 speed\n\
";
  }

  static const char* value(const ::platooning::gazupdate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::gazupdate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.distance);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gazupdate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::gazupdate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::gazupdate_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_GAZUPDATE_H
