// Generated by gencpp from file platooning/getVehicleId.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_GETVEHICLEID_H
#define PLATOONING_MESSAGE_GETVEHICLEID_H

#include <ros/service_traits.h>


#include <platooning/getVehicleIdRequest.h>
#include <platooning/getVehicleIdResponse.h>


namespace platooning
{

struct getVehicleId
{

typedef getVehicleIdRequest Request;
typedef getVehicleIdResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct getVehicleId
} // namespace platooning


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::platooning::getVehicleId > {
  static const char* value()
  {
    return "5c96f4b8297034815b56c1d26627cd99";
  }

  static const char* value(const ::platooning::getVehicleId&) { return value(); }
};

template<>
struct DataType< ::platooning::getVehicleId > {
  static const char* value()
  {
    return "platooning/getVehicleId";
  }

  static const char* value(const ::platooning::getVehicleId&) { return value(); }
};


// service_traits::MD5Sum< ::platooning::getVehicleIdRequest> should match 
// service_traits::MD5Sum< ::platooning::getVehicleId > 
template<>
struct MD5Sum< ::platooning::getVehicleIdRequest>
{
  static const char* value()
  {
    return MD5Sum< ::platooning::getVehicleId >::value();
  }
  static const char* value(const ::platooning::getVehicleIdRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::platooning::getVehicleIdRequest> should match 
// service_traits::DataType< ::platooning::getVehicleId > 
template<>
struct DataType< ::platooning::getVehicleIdRequest>
{
  static const char* value()
  {
    return DataType< ::platooning::getVehicleId >::value();
  }
  static const char* value(const ::platooning::getVehicleIdRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::platooning::getVehicleIdResponse> should match 
// service_traits::MD5Sum< ::platooning::getVehicleId > 
template<>
struct MD5Sum< ::platooning::getVehicleIdResponse>
{
  static const char* value()
  {
    return MD5Sum< ::platooning::getVehicleId >::value();
  }
  static const char* value(const ::platooning::getVehicleIdResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::platooning::getVehicleIdResponse> should match 
// service_traits::DataType< ::platooning::getVehicleId > 
template<>
struct DataType< ::platooning::getVehicleIdResponse>
{
  static const char* value()
  {
    return DataType< ::platooning::getVehicleId >::value();
  }
  static const char* value(const ::platooning::getVehicleIdResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLATOONING_MESSAGE_GETVEHICLEID_H
