// Generated by gencpp from file platooning/oughtData.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_OUGHTDATA_H
#define PLATOONING_MESSAGE_OUGHTDATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct oughtData_
{
  typedef oughtData_<ContainerAllocator> Type;

  oughtData_()
    : distance(0.0)
    , speed(0.0)
    , steeringAngle(0.0)  {
    }
  oughtData_(const ContainerAllocator& _alloc)
    : distance(0.0)
    , speed(0.0)
    , steeringAngle(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;

   typedef float _speed_type;
  _speed_type speed;

   typedef float _steeringAngle_type;
  _steeringAngle_type steeringAngle;





  typedef boost::shared_ptr< ::platooning::oughtData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::oughtData_<ContainerAllocator> const> ConstPtr;

}; // struct oughtData_

typedef ::platooning::oughtData_<std::allocator<void> > oughtData;

typedef boost::shared_ptr< ::platooning::oughtData > oughtDataPtr;
typedef boost::shared_ptr< ::platooning::oughtData const> oughtDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::oughtData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::oughtData_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::oughtData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::oughtData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::oughtData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::oughtData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::oughtData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::oughtData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::oughtData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5d11ac8cfd9baa9abe3a207005a675b7";
  }

  static const char* value(const ::platooning::oughtData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5d11ac8cfd9baa9aULL;
  static const uint64_t static_value2 = 0xbe3a207005a675b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::oughtData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/oughtData";
  }

  static const char* value(const ::platooning::oughtData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::oughtData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 distance\n\
float32 speed\n\
float32 steeringAngle\n\
";
  }

  static const char* value(const ::platooning::oughtData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::oughtData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
      stream.next(m.speed);
      stream.next(m.steeringAngle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct oughtData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::oughtData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::oughtData_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "steeringAngle: ";
    Printer<float>::stream(s, indent + "  ", v.steeringAngle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_OUGHTDATA_H
