// Generated by gencpp from file platooning/platoonProtocol.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_PLATOONPROTOCOL_H
#define PLATOONING_MESSAGE_PLATOONPROTOCOL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct platoonProtocol_
{
  typedef platoonProtocol_<ContainerAllocator> Type;

  platoonProtocol_()
    : payload()
    , message_type(0)  {
    }
  platoonProtocol_(const ContainerAllocator& _alloc)
    : payload(_alloc)
    , message_type(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _payload_type;
  _payload_type payload;

   typedef uint32_t _message_type_type;
  _message_type_type message_type;





  typedef boost::shared_ptr< ::platooning::platoonProtocol_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::platoonProtocol_<ContainerAllocator> const> ConstPtr;

}; // struct platoonProtocol_

typedef ::platooning::platoonProtocol_<std::allocator<void> > platoonProtocol;

typedef boost::shared_ptr< ::platooning::platoonProtocol > platoonProtocolPtr;
typedef boost::shared_ptr< ::platooning::platoonProtocol const> platoonProtocolConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::platoonProtocol_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::platoonProtocol_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::platoonProtocol_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::platoonProtocol_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::platoonProtocol_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::platoonProtocol_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::platoonProtocol_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::platoonProtocol_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::platoonProtocol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d9bea63af715371a2b1507d7c3fd0da2";
  }

  static const char* value(const ::platooning::platoonProtocol_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd9bea63af715371aULL;
  static const uint64_t static_value2 = 0x2b1507d7c3fd0da2ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::platoonProtocol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/platoonProtocol";
  }

  static const char* value(const ::platooning::platoonProtocol_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::platoonProtocol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string payload\n\
uint32 message_type\n\
";
  }

  static const char* value(const ::platooning::platoonProtocol_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::platoonProtocol_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.payload);
      stream.next(m.message_type);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct platoonProtocol_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::platoonProtocol_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::platoonProtocol_<ContainerAllocator>& v)
  {
    s << indent << "payload: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.payload);
    s << indent << "message_type: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.message_type);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_PLATOONPROTOCOL_H
