// Generated by gencpp from file platooning/platooningState.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_PLATOONINGSTATE_H
#define PLATOONING_MESSAGE_PLATOONINGSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct platooningState_
{
  typedef platooningState_<ContainerAllocator> Type;

  platooningState_()
    : platooning_state()
    , platoon_id(0)
    , ipd(0.0)
    , ps(0.0)
    , vehicle_id(0)
    , i_am_FV(false)
    , i_am_LV(false)
    , platoon_members()  {
    }
  platooningState_(const ContainerAllocator& _alloc)
    : platooning_state(_alloc)
    , platoon_id(0)
    , ipd(0.0)
    , ps(0.0)
    , vehicle_id(0)
    , i_am_FV(false)
    , i_am_LV(false)
    , platoon_members(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _platooning_state_type;
  _platooning_state_type platooning_state;

   typedef uint32_t _platoon_id_type;
  _platoon_id_type platoon_id;

   typedef float _ipd_type;
  _ipd_type ipd;

   typedef float _ps_type;
  _ps_type ps;

   typedef uint32_t _vehicle_id_type;
  _vehicle_id_type vehicle_id;

   typedef uint8_t _i_am_FV_type;
  _i_am_FV_type i_am_FV;

   typedef uint8_t _i_am_LV_type;
  _i_am_LV_type i_am_LV;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _platoon_members_type;
  _platoon_members_type platoon_members;





  typedef boost::shared_ptr< ::platooning::platooningState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::platooningState_<ContainerAllocator> const> ConstPtr;

}; // struct platooningState_

typedef ::platooning::platooningState_<std::allocator<void> > platooningState;

typedef boost::shared_ptr< ::platooning::platooningState > platooningStatePtr;
typedef boost::shared_ptr< ::platooning::platooningState const> platooningStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::platooningState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::platooningState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::platooningState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::platooningState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::platooningState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::platooningState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::platooningState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::platooningState_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::platooningState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "513c3389662a56c9d5dc40bcbdf23890";
  }

  static const char* value(const ::platooning::platooningState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x513c3389662a56c9ULL;
  static const uint64_t static_value2 = 0xd5dc40bcbdf23890ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::platooningState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/platooningState";
  }

  static const char* value(const ::platooning::platooningState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::platooningState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string platooning_state\n\
uint32 platoon_id\n\
float32 ipd\n\
float32 ps\n\
uint32 vehicle_id\n\
bool i_am_FV\n\
bool i_am_LV\n\
uint32[] platoon_members\n\
";
  }

  static const char* value(const ::platooning::platooningState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::platooningState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.platooning_state);
      stream.next(m.platoon_id);
      stream.next(m.ipd);
      stream.next(m.ps);
      stream.next(m.vehicle_id);
      stream.next(m.i_am_FV);
      stream.next(m.i_am_LV);
      stream.next(m.platoon_members);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct platooningState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::platooningState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::platooningState_<ContainerAllocator>& v)
  {
    s << indent << "platooning_state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.platooning_state);
    s << indent << "platoon_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.platoon_id);
    s << indent << "ipd: ";
    Printer<float>::stream(s, indent + "  ", v.ipd);
    s << indent << "ps: ";
    Printer<float>::stream(s, indent + "  ", v.ps);
    s << indent << "vehicle_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.vehicle_id);
    s << indent << "i_am_FV: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.i_am_FV);
    s << indent << "i_am_LV: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.i_am_LV);
    s << indent << "platoon_members[]" << std::endl;
    for (size_t i = 0; i < v.platoon_members.size(); ++i)
    {
      s << indent << "  platoon_members[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.platoon_members[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_PLATOONINGSTATE_H
