// Generated by gencpp from file platooning/registerTestcases.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_REGISTERTESTCASES_H
#define PLATOONING_MESSAGE_REGISTERTESTCASES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct registerTestcases_
{
  typedef registerTestcases_<ContainerAllocator> Type;

  registerTestcases_()
    : testcase()  {
    }
  registerTestcases_(const ContainerAllocator& _alloc)
    : testcase(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _testcase_type;
  _testcase_type testcase;





  typedef boost::shared_ptr< ::platooning::registerTestcases_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::registerTestcases_<ContainerAllocator> const> ConstPtr;

}; // struct registerTestcases_

typedef ::platooning::registerTestcases_<std::allocator<void> > registerTestcases;

typedef boost::shared_ptr< ::platooning::registerTestcases > registerTestcasesPtr;
typedef boost::shared_ptr< ::platooning::registerTestcases const> registerTestcasesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::registerTestcases_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::registerTestcases_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::registerTestcases_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::registerTestcases_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::registerTestcases_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::registerTestcases_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::registerTestcases_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::registerTestcases_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::registerTestcases_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1ec9035577ebb432d9345a861e195f6";
  }

  static const char* value(const ::platooning::registerTestcases_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1ec9035577ebb43ULL;
  static const uint64_t static_value2 = 0x2d9345a861e195f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::registerTestcases_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/registerTestcases";
  }

  static const char* value(const ::platooning::registerTestcases_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::registerTestcases_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string testcase\n\
";
  }

  static const char* value(const ::platooning::registerTestcases_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::registerTestcases_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.testcase);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct registerTestcases_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::registerTestcases_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::registerTestcases_<ContainerAllocator>& v)
  {
    s << indent << "testcase: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.testcase);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_REGISTERTESTCASES_H
