// Generated by gencpp from file platooning/remotecontrolInput.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_REMOTECONTROLINPUT_H
#define PLATOONING_MESSAGE_REMOTECONTROLINPUT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct remotecontrolInput_
{
  typedef remotecontrolInput_<ContainerAllocator> Type;

  remotecontrolInput_()
    : remote_speed(0.0)
    , remote_angle(0.0)
    , emergency_stop(false)  {
    }
  remotecontrolInput_(const ContainerAllocator& _alloc)
    : remote_speed(0.0)
    , remote_angle(0.0)
    , emergency_stop(false)  {
  (void)_alloc;
    }



   typedef float _remote_speed_type;
  _remote_speed_type remote_speed;

   typedef float _remote_angle_type;
  _remote_angle_type remote_angle;

   typedef uint8_t _emergency_stop_type;
  _emergency_stop_type emergency_stop;





  typedef boost::shared_ptr< ::platooning::remotecontrolInput_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::remotecontrolInput_<ContainerAllocator> const> ConstPtr;

}; // struct remotecontrolInput_

typedef ::platooning::remotecontrolInput_<std::allocator<void> > remotecontrolInput;

typedef boost::shared_ptr< ::platooning::remotecontrolInput > remotecontrolInputPtr;
typedef boost::shared_ptr< ::platooning::remotecontrolInput const> remotecontrolInputConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::remotecontrolInput_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::remotecontrolInput_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::remotecontrolInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::remotecontrolInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::remotecontrolInput_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::remotecontrolInput_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::remotecontrolInput_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::remotecontrolInput_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::remotecontrolInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "893b90aabdb4526f8be41f8f7b297e01";
  }

  static const char* value(const ::platooning::remotecontrolInput_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x893b90aabdb4526fULL;
  static const uint64_t static_value2 = 0x8be41f8f7b297e01ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::remotecontrolInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/remotecontrolInput";
  }

  static const char* value(const ::platooning::remotecontrolInput_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::remotecontrolInput_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 remote_speed\n\
float32 remote_angle\n\
bool emergency_stop\n\
";
  }

  static const char* value(const ::platooning::remotecontrolInput_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::remotecontrolInput_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.remote_speed);
      stream.next(m.remote_angle);
      stream.next(m.emergency_stop);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct remotecontrolInput_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::remotecontrolInput_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::remotecontrolInput_<ContainerAllocator>& v)
  {
    s << indent << "remote_speed: ";
    Printer<float>::stream(s, indent + "  ", v.remote_speed);
    s << indent << "remote_angle: ";
    Printer<float>::stream(s, indent + "  ", v.remote_angle);
    s << indent << "emergency_stop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergency_stop);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_REMOTECONTROLINPUT_H
