// Generated by gencpp from file platooning/remotecontrolToggle.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_REMOTECONTROLTOGGLE_H
#define PLATOONING_MESSAGE_REMOTECONTROLTOGGLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct remotecontrolToggle_
{
  typedef remotecontrolToggle_<ContainerAllocator> Type;

  remotecontrolToggle_()
    : vehicle_id(0)
    , enable_remotecontrol(false)  {
    }
  remotecontrolToggle_(const ContainerAllocator& _alloc)
    : vehicle_id(0)
    , enable_remotecontrol(false)  {
  (void)_alloc;
    }



   typedef uint32_t _vehicle_id_type;
  _vehicle_id_type vehicle_id;

   typedef uint8_t _enable_remotecontrol_type;
  _enable_remotecontrol_type enable_remotecontrol;





  typedef boost::shared_ptr< ::platooning::remotecontrolToggle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::remotecontrolToggle_<ContainerAllocator> const> ConstPtr;

}; // struct remotecontrolToggle_

typedef ::platooning::remotecontrolToggle_<std::allocator<void> > remotecontrolToggle;

typedef boost::shared_ptr< ::platooning::remotecontrolToggle > remotecontrolTogglePtr;
typedef boost::shared_ptr< ::platooning::remotecontrolToggle const> remotecontrolToggleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::remotecontrolToggle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::remotecontrolToggle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::remotecontrolToggle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::remotecontrolToggle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::remotecontrolToggle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::remotecontrolToggle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::remotecontrolToggle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::remotecontrolToggle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::remotecontrolToggle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f56e4c7d94d4f505d773a5b64c0ffed";
  }

  static const char* value(const ::platooning::remotecontrolToggle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f56e4c7d94d4f50ULL;
  static const uint64_t static_value2 = 0x5d773a5b64c0ffedULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::remotecontrolToggle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/remotecontrolToggle";
  }

  static const char* value(const ::platooning::remotecontrolToggle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::remotecontrolToggle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 vehicle_id\n\
bool enable_remotecontrol\n\
";
  }

  static const char* value(const ::platooning::remotecontrolToggle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::remotecontrolToggle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.vehicle_id);
      stream.next(m.enable_remotecontrol);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct remotecontrolToggle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::remotecontrolToggle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::remotecontrolToggle_<ContainerAllocator>& v)
  {
    s << indent << "vehicle_id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.vehicle_id);
    s << indent << "enable_remotecontrol: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.enable_remotecontrol);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_REMOTECONTROLTOGGLE_H
