// Generated by gencpp from file platooning/runTestCommand.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_RUNTESTCOMMAND_H
#define PLATOONING_MESSAGE_RUNTESTCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct runTestCommand_
{
  typedef runTestCommand_<ContainerAllocator> Type;

  runTestCommand_()
    : testToRun()  {
    }
  runTestCommand_(const ContainerAllocator& _alloc)
    : testToRun(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _testToRun_type;
  _testToRun_type testToRun;





  typedef boost::shared_ptr< ::platooning::runTestCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::runTestCommand_<ContainerAllocator> const> ConstPtr;

}; // struct runTestCommand_

typedef ::platooning::runTestCommand_<std::allocator<void> > runTestCommand;

typedef boost::shared_ptr< ::platooning::runTestCommand > runTestCommandPtr;
typedef boost::shared_ptr< ::platooning::runTestCommand const> runTestCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::runTestCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::runTestCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::runTestCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::runTestCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::runTestCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::runTestCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::runTestCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::runTestCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::runTestCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "01c8c3a6d2ae4ece1652d4c711eb8664";
  }

  static const char* value(const ::platooning::runTestCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x01c8c3a6d2ae4eceULL;
  static const uint64_t static_value2 = 0x1652d4c711eb8664ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::runTestCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/runTestCommand";
  }

  static const char* value(const ::platooning::runTestCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::runTestCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string testToRun\n\
";
  }

  static const char* value(const ::platooning::runTestCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::runTestCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.testToRun);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct runTestCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::runTestCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::runTestCommand_<ContainerAllocator>& v)
  {
    s << indent << "testToRun: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.testToRun);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_RUNTESTCOMMAND_H
