// Generated by gencpp from file platooning/stmupdate.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_STMUPDATE_H
#define PLATOONING_MESSAGE_STMUPDATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct stmupdate_
{
  typedef stmupdate_<ContainerAllocator> Type;

  stmupdate_()
    : id(0)
    , acceleration(0.0)
    , steeringAngle(0.0)  {
    }
  stmupdate_(const ContainerAllocator& _alloc)
    : id(0)
    , acceleration(0.0)
    , steeringAngle(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef float _acceleration_type;
  _acceleration_type acceleration;

   typedef float _steeringAngle_type;
  _steeringAngle_type steeringAngle;





  typedef boost::shared_ptr< ::platooning::stmupdate_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::stmupdate_<ContainerAllocator> const> ConstPtr;

}; // struct stmupdate_

typedef ::platooning::stmupdate_<std::allocator<void> > stmupdate;

typedef boost::shared_ptr< ::platooning::stmupdate > stmupdatePtr;
typedef boost::shared_ptr< ::platooning::stmupdate const> stmupdateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::stmupdate_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::stmupdate_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::stmupdate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::stmupdate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::stmupdate_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::stmupdate_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::stmupdate_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::stmupdate_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::stmupdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "85aa0214068a35b3ce74e798a0c59f18";
  }

  static const char* value(const ::platooning::stmupdate_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x85aa0214068a35b3ULL;
  static const uint64_t static_value2 = 0xce74e798a0c59f18ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::stmupdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/stmupdate";
  }

  static const char* value(const ::platooning::stmupdate_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::stmupdate_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n\
float32 acceleration\n\
float32 steeringAngle\n\
";
  }

  static const char* value(const ::platooning::stmupdate_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::stmupdate_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.acceleration);
      stream.next(m.steeringAngle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct stmupdate_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::stmupdate_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::stmupdate_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "acceleration: ";
    Printer<float>::stream(s, indent + "  ", v.acceleration);
    s << indent << "steeringAngle: ";
    Printer<float>::stream(s, indent + "  ", v.steeringAngle);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_STMUPDATE_H
