// Generated by gencpp from file platooning/targetSpeed.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_TARGETSPEED_H
#define PLATOONING_MESSAGE_TARGETSPEED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct targetSpeed_
{
  typedef targetSpeed_<ContainerAllocator> Type;

  targetSpeed_()
    : target_speed(0.0)  {
    }
  targetSpeed_(const ContainerAllocator& _alloc)
    : target_speed(0.0)  {
  (void)_alloc;
    }



   typedef float _target_speed_type;
  _target_speed_type target_speed;





  typedef boost::shared_ptr< ::platooning::targetSpeed_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::targetSpeed_<ContainerAllocator> const> ConstPtr;

}; // struct targetSpeed_

typedef ::platooning::targetSpeed_<std::allocator<void> > targetSpeed;

typedef boost::shared_ptr< ::platooning::targetSpeed > targetSpeedPtr;
typedef boost::shared_ptr< ::platooning::targetSpeed const> targetSpeedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::targetSpeed_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::targetSpeed_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::targetSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::targetSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::targetSpeed_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::targetSpeed_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::targetSpeed_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::targetSpeed_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::targetSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a0e65cab2c5b59829b64f16ffc712119";
  }

  static const char* value(const ::platooning::targetSpeed_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa0e65cab2c5b5982ULL;
  static const uint64_t static_value2 = 0x9b64f16ffc712119ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::targetSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/targetSpeed";
  }

  static const char* value(const ::platooning::targetSpeed_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::targetSpeed_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 target_speed\n\
";
  }

  static const char* value(const ::platooning::targetSpeed_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::targetSpeed_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct targetSpeed_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::targetSpeed_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::targetSpeed_<ContainerAllocator>& v)
  {
    s << indent << "target_speed: ";
    Printer<float>::stream(s, indent + "  ", v.target_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_TARGETSPEED_H
