// Generated by gencpp from file platooning/templateMsg.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_TEMPLATEMSG_H
#define PLATOONING_MESSAGE_TEMPLATEMSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct templateMsg_
{
  typedef templateMsg_<ContainerAllocator> Type;

  templateMsg_()
    : templatebool(false)
    , templatefloat(0.0)
    , templatestring()  {
    }
  templateMsg_(const ContainerAllocator& _alloc)
    : templatebool(false)
    , templatefloat(0.0)
    , templatestring(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _templatebool_type;
  _templatebool_type templatebool;

   typedef double _templatefloat_type;
  _templatefloat_type templatefloat;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _templatestring_type;
  _templatestring_type templatestring;





  typedef boost::shared_ptr< ::platooning::templateMsg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::templateMsg_<ContainerAllocator> const> ConstPtr;

}; // struct templateMsg_

typedef ::platooning::templateMsg_<std::allocator<void> > templateMsg;

typedef boost::shared_ptr< ::platooning::templateMsg > templateMsgPtr;
typedef boost::shared_ptr< ::platooning::templateMsg const> templateMsgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::templateMsg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::templateMsg_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::templateMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::templateMsg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::templateMsg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::templateMsg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::templateMsg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::templateMsg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::templateMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "06f3640a725749b7cc7a9141d075f992";
  }

  static const char* value(const ::platooning::templateMsg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x06f3640a725749b7ULL;
  static const uint64_t static_value2 = 0xcc7a9141d075f992ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::templateMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/templateMsg";
  }

  static const char* value(const ::platooning::templateMsg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::templateMsg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool templatebool\n\
float64 templatefloat\n\
string templatestring\n\
";
  }

  static const char* value(const ::platooning::templateMsg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::templateMsg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.templatebool);
      stream.next(m.templatefloat);
      stream.next(m.templatestring);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct templateMsg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::templateMsg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::templateMsg_<ContainerAllocator>& v)
  {
    s << indent << "templatebool: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.templatebool);
    s << indent << "templatefloat: ";
    Printer<double>::stream(s, indent + "  ", v.templatefloat);
    s << indent << "templatestring: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.templatestring);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_TEMPLATEMSG_H
