// Generated by gencpp from file platooning/testResult.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_TESTRESULT_H
#define PLATOONING_MESSAGE_TESTRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct testResult_
{
  typedef testResult_<ContainerAllocator> Type;

  testResult_()
    : success(false)
    , comment()  {
    }
  testResult_(const ContainerAllocator& _alloc)
    : success(false)
    , comment(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _comment_type;
  _comment_type comment;





  typedef boost::shared_ptr< ::platooning::testResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::testResult_<ContainerAllocator> const> ConstPtr;

}; // struct testResult_

typedef ::platooning::testResult_<std::allocator<void> > testResult;

typedef boost::shared_ptr< ::platooning::testResult > testResultPtr;
typedef boost::shared_ptr< ::platooning::testResult const> testResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::testResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::testResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::testResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::testResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::testResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::testResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::testResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::testResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::testResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1e664c0b6b9801e28898f96d696eb445";
  }

  static const char* value(const ::platooning::testResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1e664c0b6b9801e2ULL;
  static const uint64_t static_value2 = 0x8898f96d696eb445ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::testResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/testResult";
  }

  static const char* value(const ::platooning::testResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::testResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
string comment\n\
";
  }

  static const char* value(const ::platooning::testResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::testResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.comment);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct testResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::testResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::testResult_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    s << indent << "comment: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.comment);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_TESTRESULT_H
