// Generated by gencpp from file platooning/vehiclecontrol.msg
// DO NOT EDIT!


#ifndef PLATOONING_MESSAGE_VEHICLECONTROL_H
#define PLATOONING_MESSAGE_VEHICLECONTROL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace platooning
{
template <class ContainerAllocator>
struct vehiclecontrol_
{
  typedef vehiclecontrol_<ContainerAllocator> Type;

  vehiclecontrol_()
    : accelleration(0.0)
    , steering(0.0)  {
    }
  vehiclecontrol_(const ContainerAllocator& _alloc)
    : accelleration(0.0)
    , steering(0.0)  {
  (void)_alloc;
    }



   typedef float _accelleration_type;
  _accelleration_type accelleration;

   typedef float _steering_type;
  _steering_type steering;





  typedef boost::shared_ptr< ::platooning::vehiclecontrol_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::platooning::vehiclecontrol_<ContainerAllocator> const> ConstPtr;

}; // struct vehiclecontrol_

typedef ::platooning::vehiclecontrol_<std::allocator<void> > vehiclecontrol;

typedef boost::shared_ptr< ::platooning::vehiclecontrol > vehiclecontrolPtr;
typedef boost::shared_ptr< ::platooning::vehiclecontrol const> vehiclecontrolConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::platooning::vehiclecontrol_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::platooning::vehiclecontrol_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace platooning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/lunar/share/std_msgs/cmake/../msg'], 'platooning': ['/home/stepo/workspace/autonomesfahren/Gruppe-C/catkin_ws/src/platooning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::platooning::vehiclecontrol_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::platooning::vehiclecontrol_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::vehiclecontrol_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::platooning::vehiclecontrol_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::vehiclecontrol_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::platooning::vehiclecontrol_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::platooning::vehiclecontrol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "41ed81cddf0d4f2bc76ecf491da03a04";
  }

  static const char* value(const ::platooning::vehiclecontrol_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x41ed81cddf0d4f2bULL;
  static const uint64_t static_value2 = 0xc76ecf491da03a04ULL;
};

template<class ContainerAllocator>
struct DataType< ::platooning::vehiclecontrol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "platooning/vehiclecontrol";
  }

  static const char* value(const ::platooning::vehiclecontrol_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::platooning::vehiclecontrol_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 accelleration\n\
float32 steering\n\
";
  }

  static const char* value(const ::platooning::vehiclecontrol_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::platooning::vehiclecontrol_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.accelleration);
      stream.next(m.steering);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vehiclecontrol_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::platooning::vehiclecontrol_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::platooning::vehiclecontrol_<ContainerAllocator>& v)
  {
    s << indent << "accelleration: ";
    Printer<float>::stream(s, indent + "  ", v.accelleration);
    s << indent << "steering: ";
    Printer<float>::stream(s, indent + "  ", v.steering);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLATOONING_MESSAGE_VEHICLECONTROL_H
